### PR TITLE
Setting new frontend

### LINKED ISSUE #98: Frontend environment setting
- [x] CI
- [x] eslint
- [x] .gitignore
- [x] package.json
- [x] README.md

### PR DESCRIPTION
**Pull request by sonowz**
Basic settings are done.

See [create-nuxt-app commit](https://github.com/dnsdhrj/graduate-adventure/pull/101/commits/93dfab632b0bc0ff89f7bde858c62fc53c17252c) to find what's added.

`nuxt` uses & overrides many `webpack` settings, so I think no `webpack` plugins are required.
(For example, it automatically uglifies code in production)

File templates were made using `create-nuxt-app`. [github](https://github.com/nuxt-community/create-nuxt-app)
I also included `element-ui` using `create-nuxt-app`.
File structure can be modified if anyone wants to.

Closes #98 .

### CODE REVIEW

**Review by Jhuni0123 — APPROVED** [review]
Good. Then we should choose between element-ui and matirial design...

**Comment by sonowz** [comment]
Fixed typos in commit message.

**Comment by Jhuni0123** [comment]
But, Let's use Vuetify!

**Comment by sonowz** [comment]
Created template with `vuetify`.

**Pull request merged**
